// ─── HTML Sanitization (XSS Prevention) ────────────────────────
//
// Uses DOMPurify (via isomorphic-dompurify for Node.js compatibility)
// to strip malicious HTML/JavaScript from rich text content before
// storage and rendering.
//
// DOMPurify allows safe HTML tags that TipTap generates (bold, italic,
// headings, lists, links, etc.) while removing dangerous elements
// like <script>, <iframe>, <object>, event handlers (onclick=...),
// javascript: URLs, and other XSS vectors.
//
// Reference: https://github.com/cure53/DOMPurify

import DOMPurify from 'isomorphic-dompurify';

// ─── Allowed Tags ─────────────────────────────────────────────
//
// These are the HTML tags that TipTap's StarterKit generates.
// All other tags (script, iframe, object, embed, style, etc.)
// are stripped by DOMPurify by default.

const ALLOWED_TAGS = [
  // Block elements
  'p', 'div', 'br', 'hr',
  // Headings
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  // Text formatting
  'strong', 'b', 'em', 'i', 'u', 's', 'del', 'ins', 'sub', 'sup',
  'mark', 'small', 'span',
  // Lists
  'ul', 'ol', 'li',
  // Links
  'a',
  // Code
  'code', 'pre',
  // Blockquotes
  'blockquote',
  // Tables (future TipTap extension support)
  'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption',
  'colgroup', 'col',
  // Media
  'img', 'figure', 'figcaption',
];

// ─── Allowed Attributes ───────────────────────────────────────

const ALLOWED_ATTR = [
  // Links
  'href', 'target', 'rel', 'title',
  // Images
  'src', 'alt', 'width', 'height', 'loading',
  // Code / prose styling
  'class',
  // Tables
  'colspan', 'rowspan', 'scope',
  // Lists
  'start', 'reversed', 'type',
  // IDs for anchor linking
  'id',
];

// ─── Sanitize HTML ────────────────────────────────────────────

/**
 * Sanitize an HTML string to prevent XSS attacks.
 *
 * - Strips dangerous tags (script, iframe, object, etc.)
 * - Removes event handler attributes (onclick, onload, etc.)
 * - Blocks javascript: URLs and other dangerous URI schemes
 * - Allows safe HTML tags generated by TipTap
 *
 * @param html - Raw HTML string to sanitize (may be null/undefined)
 * @returns Sanitized HTML safe for rendering with dangerouslySetInnerHTML
 *
 * @example
 * ```ts
 * sanitizeHtml('<p>Safe content</p>') // '<p>Safe content</p>'
 * sanitizeHtml('<script>alert("xss")</script>') // ''
 * sanitizeHtml('<img src=x onerror=alert(1)>') // '<img src="x">'
 * ```
 */
export function sanitizeHtml(html: string | null | undefined): string {
  if (!html) return '';

  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    // Allow only safe URL schemes in href/src attributes
    ALLOWED_URI_REGEXP: /^(?:(?:https?|ftp|mailto|tel):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i,
    // Disallow data attributes — they're not needed and can be used for data exfiltration
    ALLOW_DATA_ATTR: false,
    // Default is true — keeps content when parent is removed (e.g., remove script but keep text)
    KEEP_CONTENT: true,
    // Return sanitized HTML as string
    RETURN_DOM: false,
    RETURN_DOM_FRAGMENT: false,
    RETURN_TRUSTED_TYPE: false,
  });
}

/**
 * Sanitize HTML content for a single rich-text field.
 * Returns null if the input is null/undefined, or the sanitized string.
 * Returns null for completely malicious input (empty after sanitization).
 */
export function sanitizeRichText(content: string | null | undefined): string | null {
  if (content === null || content === undefined) return null;
  const sanitized = sanitizeHtml(content);
  // Return null for empty results (e.g. completely malicious input)
  return sanitized || null;
}
