// ─── HTML Sanitization (XSS Prevention) ────────────────────────
//
// Uses the xss library (js-xss) to strip malicious HTML/JavaScript
// from rich text content before storage and rendering.
//
// xss is a pure CJS library with no ESM-only dependencies, making it
// compatible with both the Next.js build pipeline and vitest tests.
//
// Reference: https://www.npmjs.com/package/xss

import xss from 'xss';

// ─── Allowed Tags ─────────────────────────────────────────────
//
// These are the HTML tags that TipTap's StarterKit generates.
// All other tags (script, iframe, object, embed, style, etc.)
// are stripped by default.

const ALLOWED_TAGS = [
  // Block elements
  'p',
  'div',
  'br',
  'hr',
  // Headings
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  // Text formatting
  'strong',
  'b',
  'em',
  'i',
  'u',
  's',
  'del',
  'ins',
  'sub',
  'sup',
  'mark',
  'small',
  'span',
  // Lists
  'ul',
  'ol',
  'li',
  // Links
  'a',
  // Code
  'code',
  'pre',
  // Blockquotes
  'blockquote',
  // Tables (future TipTap extension support)
  'table',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'th',
  'td',
  'caption',
  'colgroup',
  'col',
  // Media
  'img',
  'figure',
  'figcaption',
];

// ─── Allowed Attributes ───────────────────────────────────────
// xss uses a whiteList object where keys are tag names and values
// are arrays of allowed attributes. The '*' wildcard is applied
// by merging its attributes into every tag's attribute list.

const ALLOWED_ATTRIBUTES: Record<string, string[]> = {
  // Links
  a: ['href', 'target', 'rel', 'title'],
  // Images
  img: ['src', 'alt', 'width', 'height', 'loading'],
  // Tables
  td: ['colspan', 'rowspan'],
  th: ['scope', 'colspan', 'rowspan'],
  // Lists
  ol: ['start', 'reversed', 'type'],
  // Wildcard — applied to every tag
  '*': ['class', 'id'],
};

// ─── Tags to strip entirely (body + content) ──────────────────
// These are dangerous tags that should be completely removed,
// unlike unrecognized tags whose inner text is preserved.

const STRIP_BODY_TAGS = [
  'script',
  'style',
  'iframe',
  'object',
  'embed',
  'form',
  'input',
  'button',
  'textarea',
  'select',
  'option',
  'video',
  'audio',
  'canvas',
  'applet',
  'frame',
  'frameset',
  'noscript',
  'noframes',
];

// ─── Dangerous URL schemes to block ───────────────────────────
// xss blocks javascript: and vbscript: by default, but we also
// need to block data: and other schemes.

const BLOCKED_URL_SCHEMES = ['javascript:', 'vbscript:', 'data:'];

// ─── Build xss whiteList (merge '*' wildcard into every tag) ──

function buildWhiteList(): Record<string, string[]> {
  const wildcardAttrs = ALLOWED_ATTRIBUTES['*'] ?? [];
  const whiteList: Record<string, string[]> = {};

  for (const tag of ALLOWED_TAGS) {
    const tagAttrs = ALLOWED_ATTRIBUTES[tag] ?? [];
    // Merge wildcard attributes into each tag's attribute list
    whiteList[tag] = [...new Set([...tagAttrs, ...wildcardAttrs])];
  }

  return whiteList;
}

// ─── Sanitize HTML ────────────────────────────────────────────

/**
 * Sanitize an HTML string to prevent XSS attacks.
 *
 * - Strips dangerous tags (script, iframe, object, etc.)
 * - Removes event handler attributes (onclick, onload, etc.)
 * - Blocks javascript: URLs and other dangerous URI schemes
 * - Allows safe HTML tags generated by TipTap
 *
 * @param html - Raw HTML string to sanitize (may be null/undefined)
 * @returns Sanitized HTML safe for rendering with dangerouslySetInnerHTML
 *
 * @example
 * ```ts
 * sanitizeHtml('<p>Safe content</p>') // '<p>Safe content</p>'
 * sanitizeHtml('<script>alert("xss")</script>') // ''
 * sanitizeHtml('<img src=x onerror=alert(1)>') // '<img src="x">'
 * ```
 */
export function sanitizeHtml(html: string | null | undefined): string {
  if (!html) return '';

  return xss(html, {
    whiteList: buildWhiteList(),
    stripIgnoreTag: true,
    stripIgnoreTagBody: STRIP_BODY_TAGS,
    // Block dangerous URL schemes in href/src attributes
    onTagAttr: (_tag: string, name: string, value: string) => {
      if (name === 'href' || name === 'src') {
        const lower = value.toLowerCase().trim();
        for (const scheme of BLOCKED_URL_SCHEMES) {
          if (lower.startsWith(scheme)) {
            // Return a replacement attribute with src/href emptied
            return `${name}=""`;
          }
        }
      }
      // Return void to keep the attribute as-is
      return;
    },
    css: {
      // Allow CSS properties that are safe
      whiteList: {
        color: true,
        'background-color': true,
        'font-size': true,
        'font-weight': true,
        'font-style': true,
        'font-family': true,
        'text-align': true,
        'text-decoration': true,
        'line-height': true,
        margin: true,
        'margin-top': true,
        'margin-right': true,
        'margin-bottom': true,
        'margin-left': true,
        padding: true,
        'padding-top': true,
        'padding-right': true,
        'padding-bottom': true,
        'padding-left': true,
        border: true,
        'border-radius': true,
        width: true,
        height: true,
        'max-width': true,
        'max-height': true,
        display: true,
        overflow: true,
        visibility: true,
        opacity: true,
        transform: true,
        transition: true,
        'box-shadow': true,
      },
    },
  }).replace(/\[removed\]/g, '');
}

/**
 * Sanitize HTML content for a single rich-text field.
 * Returns null if the input is null/undefined, or the sanitized string.
 * Returns null for completely malicious input (empty after sanitization).
 */
export function sanitizeRichText(content: string | null | undefined): string | null {
  if (content === null || content === undefined) return null;
  const sanitized = sanitizeHtml(content);
  // Return null for empty results (e.g. completely malicious input)
  return sanitized || null;
}
