// ─── HTML Sanitization (XSS Prevention) ────────────────────────
//
// Uses sanitize-html to strip malicious HTML/JavaScript from rich
// text content before storage and rendering.
//
// sanitize-html is a pure CJS library that runs server-side without
// requiring jsdom or browser APIs, avoiding ESM/CJS compatibility
// issues that isomorphic-dompurify had.
//
// Reference: https://www.npmjs.com/package/sanitize-html

import sanitize from 'sanitize-html';

// ─── Allowed Tags ─────────────────────────────────────────────
//
// These are the HTML tags that TipTap's StarterKit generates.
// All other tags (script, iframe, object, embed, style, etc.)
// are stripped by default.

const ALLOWED_TAGS = [
  // Block elements
  'p', 'div', 'br', 'hr',
  // Headings
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  // Text formatting
  'strong', 'b', 'em', 'i', 'u', 's', 'del', 'ins', 'sub', 'sup',
  'mark', 'small', 'span',
  // Lists
  'ul', 'ol', 'li',
  // Links
  'a',
  // Code
  'code', 'pre',
  // Blockquotes
  'blockquote',
  // Tables (future TipTap extension support)
  'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption',
  'colgroup', 'col',
  // Media
  'img', 'figure', 'figcaption',
];

// ─── Allowed Attributes ───────────────────────────────────────

const ALLOWED_ATTRIBUTES: Record<string, string[]> = {
  // Links
  a: ['href', 'target', 'rel', 'title'],
  // Images
  img: ['src', 'alt', 'width', 'height', 'loading'],
  // Tables
  td: ['colspan', 'rowspan'],
  th: ['scope', 'colspan', 'rowspan'],
  // Lists
  ol: ['start', 'reversed', 'type'],
  // All elements
  '*': ['class', 'id'],
};

// ─── Allowed URL Schemes ──────────────────────────────────────

const ALLOWED_SCHEMES = ['http', 'https', 'mailto', 'tel', 'ftp'];

// ─── Sanitize HTML ────────────────────────────────────────────

/**
 * Sanitize an HTML string to prevent XSS attacks.
 *
 * - Strips dangerous tags (script, iframe, object, etc.)
 * - Removes event handler attributes (onclick, onload, etc.)
 * - Blocks javascript: URLs and other dangerous URI schemes
 * - Allows safe HTML tags generated by TipTap
 *
 * @param html - Raw HTML string to sanitize (may be null/undefined)
 * @returns Sanitized HTML safe for rendering with dangerouslySetInnerHTML
 *
 * @example
 * ```ts
 * sanitizeHtml('<p>Safe content</p>') // '<p>Safe content</p>'
 * sanitizeHtml('<script>alert("xss")</script>') // ''
 * sanitizeHtml('<img src=x onerror=alert(1)>') // '<img src="x">'
 * ```
 */
export function sanitizeHtml(html: string | null | undefined): string {
  if (!html) return '';

  return sanitize(html, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRIBUTES,
    allowedSchemes: ALLOWED_SCHEMES,
    // Disallow all protocols not in the allowed list
    allowedSchemesByTag: {},
    // Remove disallowed tags and their content entirely (XSS prevention)
    disallowedTagsMode: 'discard',
    // Allow protocol-relative URLs (e.g. //example.com/image.png)
    allowProtocolRelative: true,
  });
}

/**
 * Sanitize HTML content for a single rich-text field.
 * Returns null if the input is null/undefined, or the sanitized string.
 * Returns null for completely malicious input (empty after sanitization).
 */
export function sanitizeRichText(content: string | null | undefined): string | null {
  if (content === null || content === undefined) return null;
  const sanitized = sanitizeHtml(content);
  // Return null for empty results (e.g. completely malicious input)
  return sanitized || null;
}
